/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DAO.PatioDAO;
import controller.GerenciaCliente;
import controller.GerenciaConta;
import controller.GerenciaVeiculo;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jdk.nashorn.internal.objects.NativeArray;
import model.Cliente;
import model.Conta;
import model.Patio;
import model.PatioComboboxModel;
import model.Veiculo;

/**
 *
 * @author jardel
 */
public class TelaConsultaConta extends javax.swing.JFrame {
    ArrayList<Cliente> arrayClientes = new ArrayList<>();
    GerenciaCliente gc = new GerenciaCliente();
    ArrayList<Veiculo> veiculos = new ArrayList<>();
    GerenciaVeiculo gv = new GerenciaVeiculo();
    ArrayList<Patio> patios = new ArrayList<>();
    PatioDAO patioDao = new PatioDAO();
    GerenciaConta gConta = new GerenciaConta();
    ArrayList<Conta> contas = new ArrayList<>();
    String modo;
    String filtro = "geral";
    
    private PatioComboboxModel patioComboBoxModel;
    /**
     * Creates new form TelaCadastroConta
     */
    public TelaConsultaConta() {
        initComponents();
        manipulaComponentes();
        patioComboBoxModel = new PatioComboboxModel();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        tfCodigoConta = new javax.swing.JTextField();
        tfNomeCliente = new javax.swing.JTextField();
        tfPlaca = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPesquisaConta = new javax.swing.JTable();
        tfPesquisarContaPorCodigo = new javax.swing.JTextField();
        btnPesquisaConta = new javax.swing.JButton();
        btnAtualizarContas = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfMes = new javax.swing.JTextField();
        tfAno = new javax.swing.JTextField();
        tfPago = new javax.swing.JLabel();
        tfQuantDeDiarias = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Consultar Conta");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");

        jLabel10.setText("QNTD de Diárias:");

        jLabel13.setText("Placa:");

        jLabel3.setText("Cliente:");

        jLabel2.setText("Código Conta:");

        tblPesquisaConta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cód. Conta", "Cód. Cliente", "Nome Cliente", "Placa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPesquisaConta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPesquisaContaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPesquisaConta);

        btnPesquisaConta.setText("Pesquisar");
        btnPesquisaConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaContaActionPerformed(evt);
            }
        });

        btnAtualizarContas.setText("Atualizar");
        btnAtualizarContas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarContasActionPerformed(evt);
            }
        });

        jLabel8.setText("Pesquisar por código:");

        jLabel4.setText("Mês:");

        jLabel5.setText("Ano:");

        jLabel6.setText("Situação:");

        tfPago.setText("...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addGap(18, 18, 18)
                .addComponent(btnSalvar)
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 877, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfPesquisarContaPorCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPesquisaConta)
                                .addGap(37, 37, 37)
                                .addComponent(btnAtualizarContas))
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfCodigoConta)
                                    .addComponent(tfQuantDeDiarias))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel13)
                                                .addGap(85, 85, 85)
                                                .addComponent(jLabel4))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(tfPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(tfMes, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(tfAno, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel6)
                                    .addComponent(tfPago, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPesquisaConta)
                    .addComponent(tfPesquisarContaPorCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtualizarContas))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel13)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCodigoConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPago)
                    .addComponent(tfQuantDeDiarias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if(tfMes.getText().length() > 0 
                && tfAno.getText().length() > 0
                && tfQuantDeDiarias.getText().length() > 0){
            int codCliente = Integer.parseInt(tfCodigoConta.getText());
            String placa = tfPlaca.getText();
            
            int diarias = Integer.parseInt(tfQuantDeDiarias.getText());
            int codigoConta = Integer.parseInt(tfCodigoConta.getText());
            
            String mensagem = gConta.incluirDiaria(codigoConta, diarias);
            if(mensagem.equals("ok")){
                JOptionPane.showMessageDialog(this, "Diária incluída com sucesso");
                
            }else{
                JOptionPane.showMessageDialog(this, "Não foi possível incluir essa diária: "+mensagem);
                
            }
            
        }else{
            JOptionPane.showMessageDialog(this, "Atenção, está faltando preecher algum campo!");
        }
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnAtualizarContasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarContasActionPerformed
        carregarTabelaConta();
        filtro = "geral";
    }//GEN-LAST:event_btnAtualizarContasActionPerformed

    private void btnPesquisaContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaContaActionPerformed
        String pesquisar = tfPesquisarContaPorCodigo.getText();
        try {
            int codigo = Integer.valueOf(pesquisar).intValue();

            Conta c = gConta.buscarPorCodigo(codigo);
            filtro = "pesquisa";
            if (c != null) {

                Object colunas[] = {"Cód. Conta", "Cód. Cliente", "Nome Cliente", "Placa"};
                DefaultTableModel modelo = new DefaultTableModel(colunas, 0);

                System.out.println("Código encontrado: " + c.getCodigo());
                Object linhas[] = new Object[]{
                    c.getCodigo(),
                    c.getCliente().getCodigo(),
                    c.getCliente().getNome(),
                    c.getVeiculo().getPlaca(),

                };
                modelo.addRow(linhas);

                tblPesquisaConta.setModel(modelo);

                tfCodigoConta.setText(String.valueOf(c.getCodigo()));
                tfNomeCliente.setText(c.getCliente().getNome());
                tfCodigoConta.setText(String.valueOf(c.getCliente().getCodigo()));
                
                
            } else {
                JOptionPane.showMessageDialog(this, "Não encontrado");
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ATENÇÃO! Digite somente números");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ATENÇÃO! Tente novamente");
        }
    }//GEN-LAST:event_btnPesquisaContaActionPerformed

    private void tblPesquisaContaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPesquisaContaMouseClicked
        int index = tblPesquisaConta.getSelectedRow();
        contas = null;
        contas = gConta.listar();

        if (filtro.equals("geral")) {
            if (index >= 0 && index < contas.size()) {
                Conta c = contas.get(index);

                tfCodigoConta.setText(String.valueOf(c.getCodigo()));
                tfNomeCliente.setText(c.getCliente().getNome());
                tfCodigoConta.setText(String.valueOf(c.getCliente().getCodigo()));
                tfPlaca.setText(c.getVeiculo().getPlaca());
                tfMes.setText(String.valueOf(c.getMes()));
                tfAno.setText(String.valueOf(c.getAno()));
                tfQuantDeDiarias.setText(String.valueOf(c.getDiarias()));
                String msg = c.getPaga() == false ? "Não Paga":"Paga";
                tfPago.setText(msg);
            }
        }
    }//GEN-LAST:event_tblPesquisaContaMouseClicked
    public void carregarTabelaConta(){
        //ArrayList<Conta> arrayClientes = new ArrayList<>();
        contas = null;
        contas = gConta.listar();
        
        Object colunas[] = {"Cód. Conta", "Cód. Cliente", "Nome Cliente", "Placa"};
        DefaultTableModel modelo = new DefaultTableModel(colunas, 0);

        for (int i = 0; i < contas.size(); i++) {
            Object linhas[] = new Object[]{
                contas.get(i).getCodigo(),
                contas.get(i).getCliente().getCodigo(),
                contas.get(i).getCliente().getNome(),
                contas.get(i).getVeiculo().getPlaca(),
            };
            modelo.addRow(linhas);
        }
        
        tblPesquisaConta.setModel(modelo);
    }
    
    
    public void manipulaComponentes() {
        tfCodigoConta.setEditable(false);
        tfNomeCliente.setEditable(false);
        tfPlaca.setEditable(false);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaConsultaConta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizarContas;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnPesquisaConta;
    private javax.swing.JButton btnSalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPesquisaConta;
    private javax.swing.JTextField tfAno;
    private javax.swing.JTextField tfCodigoConta;
    private javax.swing.JTextField tfMes;
    private javax.swing.JTextField tfNomeCliente;
    private javax.swing.JLabel tfPago;
    private javax.swing.JTextField tfPesquisarContaPorCodigo;
    private javax.swing.JTextField tfPlaca;
    private javax.swing.JTextField tfQuantDeDiarias;
    // End of variables declaration//GEN-END:variables
}
