/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Jardel
 */
public class TelaMain extends javax.swing.JFrame {

    /**
     * Creates new form TelaMain
     */
    public TelaMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuCliente = new javax.swing.JMenu();
        menuClienteCadastrar = new javax.swing.JMenuItem();
        menuClienteConsultar = new javax.swing.JMenuItem();
        menuVeiculo = new javax.swing.JMenu();
        menuVeiculoCadatrar = new javax.swing.JMenuItem();
        menuVeiculoConsultar = new javax.swing.JMenuItem();
        menuPatio = new javax.swing.JMenu();
        menuPatioCadastrar = new javax.swing.JMenuItem();
        menuPatioConsultar = new javax.swing.JMenuItem();
        menuConta = new javax.swing.JMenu();
        menuContaCadastrar = new javax.swing.JMenuItem();
        menuContaIncluirDiaria = new javax.swing.JMenuItem();
        menuConsultarConta = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuArquivo.setText("Arquivo");

        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuArquivo.add(jMenuItem1);

        jMenuBar1.add(menuArquivo);

        menuCliente.setText("Cliente");

        menuClienteCadastrar.setText("Cadastrar");
        menuClienteCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClienteCadastrarActionPerformed(evt);
            }
        });
        menuCliente.add(menuClienteCadastrar);

        menuClienteConsultar.setText("Consultar");
        menuClienteConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClienteConsultarActionPerformed(evt);
            }
        });
        menuCliente.add(menuClienteConsultar);

        jMenuBar1.add(menuCliente);

        menuVeiculo.setText("Veículo");

        menuVeiculoCadatrar.setText("Cadastrar");
        menuVeiculoCadatrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVeiculoCadatrarActionPerformed(evt);
            }
        });
        menuVeiculo.add(menuVeiculoCadatrar);

        menuVeiculoConsultar.setText("Consultar");
        menuVeiculoConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVeiculoConsultarActionPerformed(evt);
            }
        });
        menuVeiculo.add(menuVeiculoConsultar);

        jMenuBar1.add(menuVeiculo);

        menuPatio.setText("Patio");

        menuPatioCadastrar.setText("Cadastrar");
        menuPatioCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPatioCadastrarActionPerformed(evt);
            }
        });
        menuPatio.add(menuPatioCadastrar);

        menuPatioConsultar.setText("Consultar");
        menuPatioConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPatioConsultarActionPerformed(evt);
            }
        });
        menuPatio.add(menuPatioConsultar);

        jMenuBar1.add(menuPatio);

        menuConta.setText("Conta");

        menuContaCadastrar.setText("Cadastrar");
        menuContaCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuContaCadastrarActionPerformed(evt);
            }
        });
        menuConta.add(menuContaCadastrar);

        menuContaIncluirDiaria.setText("Incluir Diária");
        menuContaIncluirDiaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuContaIncluirDiariaActionPerformed(evt);
            }
        });
        menuConta.add(menuContaIncluirDiaria);

        menuConsultarConta.setText("Consultar Contas");
        menuConsultarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultarContaActionPerformed(evt);
            }
        });
        menuConta.add(menuConsultarConta);

        jMenuBar1.add(menuConta);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 754, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuClienteCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClienteCadastrarActionPerformed
        new TelaCadastroCliente().setVisible(true);
        
    }//GEN-LAST:event_menuClienteCadastrarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuClienteConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClienteConsultarActionPerformed
        new TelaConsultaCliente().setVisible(true);
        
    }//GEN-LAST:event_menuClienteConsultarActionPerformed

    private void menuVeiculoCadatrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVeiculoCadatrarActionPerformed
        new TelaCadastroVeiculo().setVisible(true);
        
    }//GEN-LAST:event_menuVeiculoCadatrarActionPerformed

    private void menuVeiculoConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVeiculoConsultarActionPerformed
        new TelaConsultaVeiculo().setVisible(true);
        
    }//GEN-LAST:event_menuVeiculoConsultarActionPerformed

    private void menuPatioCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPatioCadastrarActionPerformed
        new TelaCadastroPatio().setVisible(true);
        
    }//GEN-LAST:event_menuPatioCadastrarActionPerformed

    private void menuPatioConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPatioConsultarActionPerformed
        new TelaConsultaPatio().setVisible(true);
        
    }//GEN-LAST:event_menuPatioConsultarActionPerformed

    private void menuContaCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuContaCadastrarActionPerformed
        new TelaCadastroConta().setVisible(true);
        
    }//GEN-LAST:event_menuContaCadastrarActionPerformed

    private void menuContaIncluirDiariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuContaIncluirDiariaActionPerformed
        new TelaIncluirDiaria().setVisible(true);
    }//GEN-LAST:event_menuContaIncluirDiariaActionPerformed

    private void menuConsultarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultarContaActionPerformed
        new TelaConsultaConta().setVisible(true);
    }//GEN-LAST:event_menuConsultarContaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JMenu menuCliente;
    private javax.swing.JMenuItem menuClienteCadastrar;
    private javax.swing.JMenuItem menuClienteConsultar;
    private javax.swing.JMenuItem menuConsultarConta;
    private javax.swing.JMenu menuConta;
    private javax.swing.JMenuItem menuContaCadastrar;
    private javax.swing.JMenuItem menuContaIncluirDiaria;
    private javax.swing.JMenu menuPatio;
    private javax.swing.JMenuItem menuPatioCadastrar;
    private javax.swing.JMenuItem menuPatioConsultar;
    private javax.swing.JMenu menuVeiculo;
    private javax.swing.JMenuItem menuVeiculoCadatrar;
    private javax.swing.JMenuItem menuVeiculoConsultar;
    // End of variables declaration//GEN-END:variables
}
